### ISSUE TITLE
Todo before v1.0

### ISSUE THREAD

**Issue by OstlerDev** [oipwg/autominer-api#2]
- [x] Implement config file
- [x] Finish API details returning sqlite logs
- [x] Allow rent all function
- [x] Run rig rental script every `config.rentalLength` hours
- [x] Calculate weekly spent and left to spend so as to not overspend
